export const STATUS_CONFIG = [
  { key: "all",              label: "全部",      icon: "🗂️",  desc: "显示所有标签页，不做任何筛选" },
  { key: "active",           label: "当前激活",  icon: "🎯",  desc: "你当前正在查看和操作的标签页" },
  { key: "playing",          label: "播放中",    icon: "🔊",  desc: "正在播放音频或视频内容" },
  { key: "muted",            label: "已静音",    icon: "🔕",  desc: "你手动关闭了该标签页的声音" },
  { key: "pinned",           label: "已固定",    icon: "📌",  desc: "固定在标签栏左侧，防止误关闭" },
  { key: "frozen",           label: "已冻结",    icon: "🧊",  desc: "后台标签页已暂停任务以节省电量" },
  { key: "discarded",        label: "已舍弃",    icon: "🗑️",  desc: "内存不足时被卸载，点击重新加载" },
  { key: "loading",          label: "加载中",    icon: "⌛",  desc: "页面资源正在加载中，请稍候" },
  { key: "recording",        label: "录制中",    icon: "🔴",  desc: "正在使用摄像头或麦克风" },
  { key: "sharing",          label: "共享中",    icon: "📡",  desc: "正在共享屏幕或窗口" },
  { key: "attention",        label: "引起注意",  icon: "🔔",  desc: "页面弹窗或通知需要你处理" },
  { key: "hasUnsavedForm",   label: "未保存表单",icon: "📝",  desc: "包含未提交的表单数据" },
  { key: "hasConnectedDevice", label: "连接设备",icon: "🔌",  desc: "正在连接 USB、蓝牙等外部设备" },
  { key: "isProtected",      label: "受保护",    icon: "🔒",  desc: "浏览器内部页面，无法关闭" },
]
